name: Build & Relase Luminara GUI

on:
  workflow_dispatch:
    inputs:
      relsase_version:
        description: 'Version for release'
        required: true
        default: 'v0.0.1'
        
jobs:
  gui-build:
    name: Build Luminara GUI for different operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [25]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build jlink runtime
        run: mvn clean javafx:jlink # add the porfile for the cli when needed

      - uses: actions/upload-artifact@v4
        with:
          name: Luminara-GUI-${{ matrix.os }}
          path: Luminara-${{ matrix.os }}-${{ github.event.inputs.release_version }}.zip

  release-upload:
    name: Create release and upload the GUI artifacts
    needs: gui-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download GUI atrifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: ${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload GUI zips to release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/* 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
